# Generated by Django 3.1.1 on 2021-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.URLField(default='http://www.google.com', max_length=500),
        ),
    ]
