# Generated by Django 3.1.1 on 2021-08-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementapp', '0002_auto_20210801_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(default='Default Title', max_length=300),
        ),
    ]
